### ISSUE TITLE
Youtube history download sees 0 videos

### ISSUE THREAD

**Issue by lightray22** [blackjack4494/youtube-dlc#106]
I copied/pasted the following from an issue I wrote in youtube_dl @ https://github.com/ytdl-org/youtube-dl/issues/26452.  I tried youtube_dlc master today (9/13) and the same issue exists.

## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.07.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: ['-o', '%(uploader)s_%(upload_date)s_%(title)s_%(height)s_%(id)s.%(ext)s', '--continue', '--no-overwrites', '--ignore-errors', '--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 -s 16 -k 1M --console-log-level=error --file-allocation=none --keep-unfinished-download-result=false --summary-interval=0']
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/home/user/.config/youtube-dl/cookies-user.txt', '--max-filesize', '10g', '--download-archive', './.downloaded.txt', '--verbose', 'https://www.youtube.com/feed/history']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.8 (CPython) - FreeBSD-12.1-RELEASE-p8-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History

## Description

Trying to download from YouTube's history results in it showing zero videos and not downloading anything.  Using the same cookies and download.txt file but downloading from a playlist instead works fine, so I know those files are valid.  I also tried downloading the history from three different accounts and the same behavior of zero videos happens.  The last time this worked properly was July 22nd, so it seems to have been broken for a while.

Here is the exact command I'm using:

`/usr/local/bin/youtube-dl --cookies /home/user/.config/youtube-dl/cookies-user.txt --max-filesize 10g --download-archive ./.downloaded.txt --verbose https://www.youtube.com/feed/history`

**Comment by blackjack4494** [comment]
Haven't tested this. But I simply assume youtube changed something on their end. I can try to debug it and see what is happening when it's trying to download the feed info.

**Comment by blackjack4494** [comment]
Well turns out the subscription feed isn't working as well. All the other feeds don't even have URL support.

**Comment by blackjack4494** [comment]
@xarantolus
https://github.com/blackjack4494/youtube-dlc/pull/173
> PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://www.youtube.com/feed/history" -v -F --cookies .\cookies.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/feed/history', '-v', '-F', '--cookies', '.\\cookies.txt']
[debug] Loading archive file None
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dlc version 2020.09.29
[debug] Git HEAD: 60ecb525b
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 200 videos
[download] Downloading video 1 of 200
[youtube] hZSOhVdzqZk: Downloading webpage
[info] Available formats for hZSOhVdzqZk:
format code  extension  resolution note
249          webm       audio only tiny   53k , opus @ 50k (48000Hz), 18.30MiB
250          webm       audio only tiny   74k , opus @ 70k (48000Hz), 23.10MiB
140          m4a        audio only tiny  133k , m4a_dash container, mp4a.40.2@128k (44100Hz), 50.10MiB
251          webm       audio only tiny  133k , opus @160k (48000Hz), 41.90MiB
278          webm       256x144    144p   73k , webm container, vp9, 30fps, video only, 13.20MiB
160          mp4        256x144    144p  119k , avc1.4d400c, 30fps, video only, 9.82MiB
242          webm       426x240    240p  147k , vp9, 30fps, video only, 17.12MiB
133          mp4        426x240    240p  222k , avc1.4d4015, 30fps, video only, 18.69MiB
243          webm       640x360    360p  304k , vp9, 30fps, video only, 33.23MiB
134          mp4        640x360    360p  325k , avc1.4d401e, 30fps, video only, 32.04MiB
244          webm       854x480    480p  566k , vp9, 30fps, video only, 53.00MiB
135          mp4        854x480    480p  653k , avc1.4d401f, 30fps, video only, 50.44MiB
247          webm       1280x720   720p  987k , vp9, 30fps, video only, 98.92MiB
136          mp4        1280x720   720p 1206k , avc1.64001f, 30fps, video only, 94.31MiB
248          webm       1920x1080  1080p 1616k , vp9, 30fps, video only, 200.76MiB
137          mp4        1920x1080  1080p 2446k , avc1.640028, 30fps, video only, 184.57MiB
18           mp4        640x360    360p  223k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 86.31MiB
22           mp4        1280x720   720p  372k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
[download] Downloading video 2 of 200
[youtube] yyxy-KW_seI: Downloading webpage

will include the fix in the next release. It will be out in a few minutes.

**Comment by qw3rty2017** [comment]
It's only grabbing the first page of videos. (~200)
Im using "--playlist-items 1-1500" but it doesn't work.

**Comment by blackjack4494** [comment]
Yup that's due to youtube chaning apis.  
Instead of ajax they use `https://www.youtube.com/youtubei/v1/browse?key=` but the ajax sometimes still works or is used by youtube. As for the new api they changed the location/name of the token within the last 2-3 weeks. 

There is
`"INNERTUBE_API_KEY":"AIza..."` in the html doc
which is needed to make any requests to `/youtubei/v1/`
Couldn't find any sources for endpoints yet but have documented a few already maybe I will make them public when I have a nicer rewrite.
Maybe @xarantolus is interested in this as well as he wrote the feed/url extraction fix.

Entrypoint for next continuation request is embedded in html doc as well
```
{"continuationItemRenderer":{"trigger":"CONTINUATION_TRIGGER_ON_ITEM_SHOWN","continuationEndpoint":{"clickTrackingParams":"CB0...=","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true,"apiUrl":"/youtubei/v1/browse"}},"continuationCommand":{"token":"4qmFsgJ....","request":"CONTINUATION_REQUEST_TYPE_BROWSE"}}}}]
```
We just need the `token` and can send a new request with some additional mandatory parameters such as 
`authorization: SAPISIDHASH 16..._6b5c3...`
We actually need the `sapisid` which can then be fed into some algorithm to give us back a valid hash `SAPISIDHASH`  
This algorithm is quite easy
`sha1(new Date().getTime() + " " + SAPISID + " " + origin)` [[source](https://stackoverflow.com/a/32065323/1515686)]

The implementation for a fix shouldn't take long

**Comment by blackjack4494** [comment]
@qw3rty2017 
>[youtube:history] Youtube History: Downloading page #42q
[youtube:history] Youtube History: Downloading page #43q
[youtube:history] Youtube History: Downloading page #44q
[youtube:history] Youtube History: Downloading page #45q
[youtube:history] Youtube History: Downloading page #46q
[youtube:history] Youtube History: Downloading page #47q
[youtube:history] Youtube History: Downloading page #48q
[youtube:history] Youtube History: Downloading page #49q
[youtube:history] Youtube History: Downloading page #50q
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; 
see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

I added the `q`s otherwise I would ping several issues.  
I actually don't know nor believe that page 50 is the maximum. Sometimes it stops earlier like around 40-ish.  
The '500 HTTP ERROR' needs to be analzed. There is prolly some rate limiting going on.  
However I have honestly no clue how to know when to stop polling this way. As there shouldn't be any more continuation token if I am done.

But at least it is working now. Have to polish it a bit but then it's ready to be shipped with next release.
