### ISSUE TITLE
youtube-dlc.exe Trojan?

### ISSUE THREAD

**Issue by C0ldF** [blackjack4494/youtube-dlc#114]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, why windows defender says the youtube-dlc.exe its trojan?   https://prnt.sc/uhoder

**Comment by TheFrenchGhosty** [comment]
Because it's an unsigned exe that share some characteristics with real malware. 

And because antivirus are dumb and useless.

**Comment by blackjack4494** [comment]
Nothing I can do for now.  
You can indeed build it yourself if you don't trust me. Hopefully soon everything will be build automatic (including exe).

If you have python installed I suggest you using `pip install` then.

Will close this for now. But feel free to keep discussing here.

**Comment by jbruchon** [comment]
It is common for antiviruses and for Windows SmartScreen to raise concerns about binaries from open source projects. Avast Antivirus, for example, will flip out because "this file hasn't been seen by many systems yet" and will block execution until a comprehensive heuristic scan is run on the executable.

**Comment by blackjack4494** [comment]
Some AV will trigger because they haven't seen a program before. Some will trigger even if you have like one line code in common with some known malware. The only solution would be to get an expensive certificate to sign your own program (there is no free way like let's encrypt does for websites).  
I did the best I can by let the CI build on the public code.
