### ISSUE TITLE
[Site Request] Zee5.com

### ISSUE THREAD

**Issue by Ashish0804** [blackjack4494/youtube-dlc#133]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dlcc version **2020.09.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.zee5.com/tvshows/details/jodha-akbar/0-6-447/episode-1-jodha-akbar/0-1-jodhaakbar-jodhaakbarseason1-episode_1465338501
- Single video: https://www.zee5.com/tvshows/details/jodha-akbar/0-6-447/episode-1-jodha-akbar/0-1-jodhaakbar-jodhaakbarseason1-episode_1465338501
- Playlist: https://www.zee5.com/tvshows/details/jodha-akbar/0-6-447

## Description

Zee5 is an indian streaming site. It might be geo restricted and i am willing to provide vpn credentials to work on it. 
P.S. it has free aswell as paid content, only free can be downloaded and it doesn't require account to watch them.

**Comment by blackjack4494** [comment]
@Ashish0804 had some time to look into it. At first I thought it looked simple since they use kaltura somehow. But then I saw some drm related stuff. The kaltura entry_id is actually pointing to a big buck bunny video.  
No clue if situation is different if accessed from India vpn but I don't think so.

Videos without drm are the ones like this
https://www.zee5.com/global/news/details/mumbais-dabbawalas-struggling-to-make-ends-meet-amid-covid-19/0-0-newsauto_7bt38011mqc0

This is one of their apis
https://gwapi.zee5.com/content/details/0-1-jodhaakbar-jodhaakbarseason1-episode_1241229845?translation=en&country=DE&version=2
If I try to change country it outputs `{"error_code":401,"error_msg":"Token Missing"}`

Furthermore
https://useraction.zee5.com/token/platform_tokens.php?platform_name=web_app
https://useraction.zee5.com/token/
https://useraction.zee5.com/tokennd/
https://useraction.zee5.com/token/platform_tokens.php?platform_name=html5_app
https://b2bapi.zee5.com/front/countrylist.php?lang=en&ccode=DE

https://zee5vod.akamaized.net/drm1/1080p/movies/MOVIE_PROJECT/PROGRAMS/LIBRARY/ZEE_TV/Jodha_Akbar_Hindi_30062020/Jodha_Akbar_Hindi_Ep04_hi_5f2f1bb9.mp4/thumbnails/index.vtt
https://zee5vod.akamaized.net/drm1/1080p/movies/MOVIE_PROJECT/PROGRAMS/LIBRARY/ZEE_TV/Jodha_Akbar_Hindi_30062020/Jodha_Akbar_Hindi_Ep04_hi_5f2f1bb9.mp4/thumbnails/00000002.jpg

**Comment by rakesh-1729** [comment]
@blackjack4494
https://github.com/dedshit/Zee5  might be help. It able to play zee5.com videos.
I have tested with
https://www.zee5.com/zee5originals/details/abhay/0-6-1298/ep-2-one-legged-skeleton/0-1-387070
https://www.zee5.com/movies/details/donga/0-0-201265
https://www.zee5.com/zee5originals/details/amrutham-dhvitheeyam/0-6-2548/ep-2-when-failure-becomes-your-friend/0-1-manual_72r3gk4jm5h0
https://www.zee5.com/movies/details/insidious/0-0-124061
