### ISSUE TITLE
[Broken] mtv - MTV completely changed their website, and videos are no longer being detected

### ISSUE THREAD

**Issue by StevenDTX** [blackjack4494/youtube-dlc#175]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.09.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```

E:\>c:\support\youtube-dlc.exe "https://www.mtv.com/episodes/gwvbw4/16-and-pregnant-madisen-season-6-ep-1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mtv.com/episodes/gwvbw4/16-and-pregnant-madisen-season-6-ep-1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
[mtv] 16-and-pregnant-madisen-season-6-ep-1: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 287, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 213, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 39, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'

```

## Description

MTV completely changed their website, and videos are no longer being detected

**Comment by blackjack4494** [comment]
If I try to watch it in Chrome it won't because it's restricted. You need login details and maybe even vpn (since I am based in Germany). However I still could extract some information 😄 

>[mtv] 7d923db1-a492-11ea-9225-70df2f866ace: Downloading info
[mtv] ab59f422-eff8-437a-81a0-345c0cf47c85: Extracting information
[mtv] ab59f422-eff8-437a-81a0-345c0cf47c85: Downloading video urls
[mtv] ab59f422-eff8-437a-81a0-345c0cf47c85: Downloading m3u8 information
[mtv] f49153c0-cb1d-465c-aae9-98bc092191fa: Extracting information
[mtv] f49153c0-cb1d-465c-aae9-98bc092191fa: Downloading video urls
[mtv] f49153c0-cb1d-465c-aae9-98bc092191fa: Downloading m3u8 information
[mtv] 9bbd7e67-bcf9-4fb0-9626-914547a152de: Extracting information
[mtv] 9bbd7e67-bcf9-4fb0-9626-914547a152de: Downloading video urls
[mtv] 9bbd7e67-bcf9-4fb0-9626-914547a152de: Downloading m3u8 information
[mtv] eeb9e985-f025-46e5-8a36-c914bd062562: Extracting information
[mtv] eeb9e985-f025-46e5-8a36-c914bd062562: Downloading video urls
[mtv] eeb9e985-f025-46e5-8a36-c914bd062562: Downloading m3u8 information
[mtv] e332dc19-d4ad-47ce-8fa9-2e164690457e: Extracting information
[mtv] e332dc19-d4ad-47ce-8fa9-2e164690457e: Downloading video urls
[mtv] e332dc19-d4ad-47ce-8fa9-2e164690457e: Downloading m3u8 information
[mtv] 96dcb5a4-1b5a-4141-bcc0-85f8cbc76f29: Extracting information
[mtv] 96dcb5a4-1b5a-4141-bcc0-85f8cbc76f29: Downloading video urls
[mtv] 96dcb5a4-1b5a-4141-bcc0-85f8cbc76f29: Downloading m3u8 information
[download] Downloading playlist: The Prank That Hits the Jackpot
[mtv] playlist The Prank That Hits the Jackpot: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 91
[download] Destination: Revenge Prank_September 10, 2020_1_116_The Prank That Hits the Jackpot_Act 1-ab59f422-eff8-437a-81a0-345c0cf47c85.mp4
[download]  41.8% of ~23.15MiB at  3.27MiB/s ETA 00:52

Just need to figure out which video is which. I just tried to manually set the video id and see if it returns anything at all. So here we are now left with 6 results.

**Comment by StevenDTX** [comment]
> @StevenDTX could you give me some information about the duration of this video https://www.mtv.com/episodes/4iqsts/revenge-prank-the-prank-that-hits-the-jackpot-season-1-ep-16
> if you have access to it?

https://www.mtv.com/episodes/4iqsts/revenge-prank-the-prank-that-hits-the-jackpot-season-1-ep-16
Duration: 29:45. That must include ads as that series is usually 20-21 minutes.

This episode is unlocked, at least in the US. It does not require a login.
https://www.mtv.com/episodes/gwvbw4/16-and-pregnant-madisen-season-6-ep-1

I do, however, have a login if you need to perform some testing for you.

Thanks!

**Comment by blackjack4494** [comment]
@StevenDTX by any chance are you free right now? You could join gitter chat or another platform of your choice.  
It seems the video is split into 'Acts' 
2020_1_116_The Prank That Hits the Jackpot_Act 1
2020_1_116_The Prank That Hits the Jackpot_Act 2
2020_1_116_The Prank That Hits the Jackpot_Act 3
etc.  
Where the first act is ~9 minutes, next two ~4 minutes+, 4th act almost 3 minutes and the last two are 20-30 seconds each but some kind of outro and credits.  
Dunno if there is a complete version. But as you mentioned ads I may believe it's only available in parts.  
The ads itself aren't downloaded btw.

**Comment by StevenDTX** [comment]
> 
> 
> @StevenDTX by any chance are you free right now? You could join gitter chat or another platform of your choice.
> It seems the video is split into 'Acts'
> 2020_1_116_The Prank That Hits the Jackpot_Act 1
> 2020_1_116_The Prank That Hits the Jackpot_Act 2
> 2020_1_116_The Prank That Hits the Jackpot_Act 3
> etc.
> Where the first act is ~9 minutes, next two ~4 minutes+, 4th act almost 3 minutes and the last two are 20-30 seconds each but some kind of outro and credits. So around 20-21 minutes in total.
> Dunno if there is a complete version. But as you mentioned ads I may believe it's only available in parts.
> The ads itself aren't downloaded btw.

Sure. Send me a link??

**Comment by blackjack4494** [comment]
https://gitter.im/youtube-dlc/community
You should be able to log in with github if I remember correctly

**Comment by StevenDTX** [comment]
I joined the chat.

I also wanted to note that MTV has always split their shows.  Half hour shows are usually ~6 segments and hour long shows are usually 11-12.   My scripts combine them after they all download.  

However, MTV redesigned their website last week and now the videos are no longer being extracted.  With the new website, they also introduced HTTPS.

**Comment by blackjack4494** [comment]
@StevenDTX extractor is updated and new release is out. Have fun.

**Comment by StevenDTX** [comment]
> @StevenDTX extractor is updated and new release is out. Have fun.

You are awesome!  I will check it out later this morning. 

Can I buy you a beer?  I don’t see a donation link anywhere.

**Comment by StevenDTX** [comment]
The fix works great!  Thank you again.
