### ISSUE TITLE
[youtube] json3 captions

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/youtube-dlc#33]
https://github.com/extremeheat/youtube-dl/commit/775eb34079e9c539c845e7a0d4eb65d8e32ec59e

@extremeheat
@zubearc do you have any example links?

**Comment by zubearc** [comment]
That commit was a bit hacked together for my use case, I cleaned up and amended the commit at https://github.com/zubearc/youtube-dl/commit/7e1cf1a48d7b3ad2810dd0c870d3cd7dbcb4906a.

YouTube added new JSON-based captions format called "json3" (now the default) which can be appended to _SUBTITLE_FORMATS. There was another issue with the downloader not properly fetching automatic transcriptions (previously it would always select the first transcript option, [which isn't always automatic](https://gist.github.com/zubearc/55549f57c2580eb423a0d6c625a95adb)), which I also fixed. There's a lot of legacy code in the captions which can probably be removed.

**Comment by blackjack4494** [comment]
Thanks so far for the information and the updated code. I will try my best to add it to the code base as soon as I have time to do this :)

**Comment by blackjack4494** [comment]
Okay. Just checking the code now. I am a bit confused.

Why is this needed
https://github.com/extremeheat/youtube-dl/commit/775eb34079e9c539c845e7a0d4eb65d8e32ec59e#diff-bd8242a0122c5207531954b67e6e51f0R1529-R1530
and  
https://github.com/extremeheat/youtube-dl/commit/775eb34079e9c539c845e7a0d4eb65d8e32ec59e#diff-bd8242a0122c5207531954b67e6e51f0R1547-R1548

Your changes in your own fork seems to be better
https://github.com/zubearc/youtube-dl/commit/7e1cf1a48d7b3ad2810dd0c870d3cd7dbcb4906a#diff-bd8242a0122c5207531954b67e6e51f0R1563-R1577

I haven't tested them locally yet as I don't know what video can be used to test it with. So I am tending to merge your fork changes.

**Comment by zubearc** [comment]
Updated the YouTube subtitles tests at https://github.com/zubearc/youtube-dl/commit/8848f8083b23a48d07fa2edb95eee8c547b542d9.

As for CLI, can be tested with --write-auto-sub and optional --sub-format.

`python __main__.py --write-auto-sub --sub-format=json3 -f worst --id --write-info-json https://www.youtube.com/watch?v=IMcFJgDQKc4` or 
`python __main__.py --write-auto-sub --sub-format=vtt  -f worst --id --write-info-json https://www.youtube.com/watch?v=6JxMEvkZz6w` 

If it helps I can make a PR in the youtube-dl repo.

**Comment by blackjack4494** [comment]
No worry @zubearc I manually imported your repository and added it. Would have been easier if it's a fork but no problem.

It works indeed. Tho I can't wrap my head around why someone would want the json3 as it seems to be used only by youtube.  
The updated tests seem fine as well. Although this looks a bit odd
`WARNING: Couldn't find automatic captions for QRS8MkLhQmM`  
There are of course automatic captions for this video. Maybe you have a clue or I missed something. Your changes are merged next few minutes.

**Comment by zubearc** [comment]
The difference between the automatic and the manual captions are that the automatic ones are generated by YouTube and have aligned timestamps for when each word starts, whereas the manual ones usually have lines of text that appear all at once and no guarantee they're aligned or match the video. Not that big of a big deal, but they can be useful. In QRS8MkLhQmM the captions are all manually written. My use-case is for building a ML model from YouTube if that makes sense :)

As for JSON3, yeah I think it would be a good idea to replace the order of it to not be the default for users. The main benefit I see is for devs since it's a standard format easily readable in code vs. the custom formats.

**Comment by blackjack4494** [comment]
Yeah I do know what automatic captions are but was referring to this
![image](https://user-images.githubusercontent.com/4406639/92315689-c7febb80-efe9-11ea-8c1d-13b46348d19c.png)
![image](https://user-images.githubusercontent.com/4406639/92315694-d51baa80-efe9-11ea-821f-6a0da7f9c9c0.png)

Don't mind the missing json3 here. Was tested against unpatched version. But patched will output same with json3.

**Comment by zubearc** [comment]
I believe that's just listing all of the available captions instead of just the automatic ones.

Looking at the [page JSON](https://gist.github.com/zubearc/d4adfb7d9bfb5a47b559a8710de62e3e#file-qrs8mklhqmm-cap-json-L686) it seems they're all manual. Manual (non-ASR) ones are accessible through the normal YouTube API eg, https://www.youtube.com/api/timedtext?v=QRS8MkLhQmM&lang=zh-Hant

**Comment by blackjack4494** [comment]
@zubearc have to exclude json3 for now. Maybe you have a way to put on a lower priority. As it's not supported by ffmpeg now and there seems to be no parser for it either.

**Comment by zubearc** [comment]
Under SUBTITLE_FORMATS resorting json3 away from being the last entry seems
to change the default.

**Comment by blackjack4494** [comment]
Indeed. Wasn't aware of this. Thanks.
