### ISSUE TITLE
Document the fork

### ISSUE THREAD

**Issue by JensTimmerman** [blackjack4494/youtube-dlc#77]
Hi, i just came across this project because a pr of mine was merged into it and I was mentioned in the release. 

But it is unclear to me what the goal of this fork is and how it differs from YouTube-dl?

Can this please be explained a bit in the repo description or the readme?

**Comment by DavidBuchanan314** [comment]
For anyone else who was wondering, I found an explanation here: https://old.reddit.com/r/DataHoarder/comments/ir8ic6/youtubedlc_an_active_fork_of_youtubedl/

**Comment by JensTimmerman** [comment]
Thx, @DavidBuchanan314 This pointed me to https://github.com/ytdl-org/youtube-dl/issues/26462 which already answered a few questions.

**Comment by blackjack4494** [comment]
Sure you are absolutely right. So far I have avoided it and forgot it a bit. But that is an important point. Maybe it's enough in the meantime to draw attention for this in the readme and linking to reddit and the ytdl issue until I got more time.

There is a lot still missing of course. But that will change over time.

**Comment by jbruchon** [comment]
FYI, this fork does not appear when I search GitHub for "youtube-dlc."

**Comment by blackjack4494** [comment]
@jbruchon 
Yup this is due to github search. You have to explicitly include forks. But there will likely be a separate repository with a new name in the future. But before that happens there will be some more changes.

A short clarification got already added. However I may add a dedicated markdown file with some more information.
